### ISSUE TITLE
Agregar un modo oscuro. 

### ISSUE THREAD

**Issue by diloes** [midudev/preguntas-entrevista-react#66]
Estaría bien agregar un modo oscuro a la web. Con el típico interruptor para elegir dark o ligth.

**Comment by D3press3dd** [comment]
En proceso! ✌️

**Comment by mozi47** [comment]
Gracias por plantear este problema. Noté que ha estado abierto durante 8 meses sin ninguna actividad, así que decidí tomar la iniciativa e implementar la función de modo oscuro y claro. Creé una solicitud de extracción (PR) con los cambios.

Creo que esta característica mejorará la experiencia del usuario del proyecto. He seguido las pautas del proyecto y los estándares de codificación para garantizar una integración fluida. Se agradecen mucho sus comentarios y revisión del PR.

Esperamos sus opiniones y la posibilidad de fusionar esta función. 🌟

**Comment by diloes** [comment]
Excelente!! A ver si Midu tiene un ratito para mergearla.

**Comment by mozi47** [comment]
@diloes Gracias. ¡Esperemos el valioso aporte de @midudev!
