### ISSUE TITLE
Error en el Libro y la Web

### ISSUE THREAD

**Issue by Renato6GS** [midudev/preguntas-entrevista-react#76]
En la pregunta: "¿Se puede inicializar un estado con el valor de una prop? ¿Qué pasa si lo haces y qué hay que tener en cuenta?"

En el 6to párrafo (antes del segundo ejemplo de código) hay un error que dice:
"... es una buena práctica es añadir el prefijo de initial  ...."

Sugiero que se debe eliminar la segunda palabra "es" que está entre "práctica" y "añadir".

**Comment by Gato3232** [comment]
UIKitCore
