### ISSUE TITLE
Qué son los hugs?     

### ISSUE THREAD

**Issue by Molayg** [midudev/preguntas-entrevista-react#84]

**Comment by ismanolgarcia** [comment]
Saludos ! Tu pregunta es referente a los bugs o quieres decir hooks ? No la puedo comprender aunque me imagino que quieres decir Hooks

**Comment by Nor01** [comment]
Los hugs son ABRAZOS.

Los Hooks son funciones especiales que nos permitirá conectarnos a características de React para trabajar con métodos especificos, los cuales nos permitirán manejar el estado de mejor forma, sin depender de clases. ejemplo, useEffect, useState...
