### ISSUE TITLE
Faltan preguntas muy importantes

### ISSUE THREAD

**Issue by juanchistosomk** [midudev/preguntas-entrevista-react#93]
Me parece increible que no esten estas 2 preguntas tan elementales. Para alguien como yo que soy principiante  >:(

¿Cómo se instala React?????
¿Cómo se incia un nuevo proyecto en React????????

**Comment by midudev** [comment]
Este no es un repositorio para aprender React. Es un repositorio para preparar una entrevista técnica de React.

Si no sabes ni instalar React, lo mejor que puedes hacer es aprenderlo antes de venir aquí. Aquí tienes un curso: https://midu.link/react
